### ISSUE TITLE
Crack down on any fake apps

### ISSUE THREAD

**Issue by Sens365** [BLPoonia/fake-loan-apps-google-play-store-ios-app-store#1]
Hello, I am an iOS developer. I saw the App we developed on the website and hope to get your help.

For some reason, the qualified and authorized company developer account was removed by Apple, and then the subsidiary authorization method was adopted for development and release, providing Apple with the legitimacy, partnership and qualification certificates of the two companies. Practice has proved that this method is not the best. Please help me.

Persist in cracking down on any illegal and fraudulent applications.

**Comment by pooniawalla** [comment]
Hello @Sens365, Which apps are talking about? Please share all details with me, would love to help. DM me on my LinkedIn or X (Twitter).
